FROM amazoncorretto:17-al2-jdk
WORKDIR /app

# Copy everything from your GitHub repo into the container
COPY . .

# Create bin folder
RUN mkdir -p bin

# Point the compiler to the correct subfolder path
RUN javac -cp ".:NocturneArchiveProject/lib/*" $(find NocturneArchiveProject/src -name "*.java") -d bin

# Run the app from the correct bin location
CMD ["java", "-cp", "bin:NocturneArchiveProject/lib/*", "App"]