# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Compile the Java code (including the lib folder for the JDBC driver)
RUN javac -cp ".:lib/*" src/*.java -d bin

# Run the app when the container launches
CMD ["java", "-cp", "bin:lib/*", "App"]